name: Trigger auto deployment for rhel-studyapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/rhel-studyapp-AutoDeployTrigger-5cc0d9bf-91f6-4467-b62a-f6b3134fec7a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RHELSTUDYAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RHELSTUDYAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RHELSTUDYAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: docker.io
          registryUsername: ${{ secrets.RHELSTUDYAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RHELSTUDYAPP_REGISTRY_PASSWORD }}
          containerAppName: rhel-studyapp
          resourceGroup: NetworkWatcherRG
          imageToBuild: docker.io/conallmurphy/rhcsa-practice:0.1.0-rhel-studyapp-${{ github.sha }}


